version: "3.9"

volumes:
  staticfiles:
  backend_static:
  backend_media:
  pg_data:

networks:
  chemical_treatment:
    driver: bridge

services:

  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - chemical_treatment

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - backend_static:/app/backend/staticfiles/
      - backend_media:/app/backend/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - chemical_treatment
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:1.22.1
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/backend_static/
      - backend_media:/backend_media/
    networks:
      - chemical_treatment
